-- +goose Up
-- +goose StatementBegin
CREATE TYPE product_id AS ENUM(
        -- expansions
        'base',
        'get_to_work',
        'get_together',
        'city_living',
        'cats_and_dogs',
        'seasons',
        'get_famous',
        'island_living',
        'discover_university',
        'eco_lifestyle',
        'snowy_escape',
        'cottage_living',
        'high_school_years',
        'growing_together',
        'horse_ranch',
        'for_rent',
        'lovestruck',
        'life_and_death',
        'businesses_and_hobbies',
        -- game packs
        'outdoor_retreat',
        'spa_day',
        'dine_out',
        'vampires',
        'parenthood',
        'jungle_adventure',
        'strangerville',
        'realm_of_magic',
        'star_wars_journey_to_batuu',
        'dream_home_decorator',
        'my_wedding_stories',
        'werewolves',
        -- stuff packs
        'luxury_party',
        'perfect_patio',
        'cool_kitchen',
        'spooky',
        'movie_hangout',
        'romantic_garden',
        'kids_room',
        'backyard',
        'vintage_glamour',
        'bowling_night',
        'fitness',
        'toddler',
        'laundry_day',
        'my_first_pet',
        'moschino',
        'tiny_living',
        'nifty_knitting',
        'paranormal',
        'home_chef_hustle',
        'crystal_creations',
        -- kits
        'throwback_fit',
        'country_kitchen',
        'bust_the_dust',
        'courtyard_oasis',
        'modern_menswear',
        'carnaval_streetwear',
        'decor_to_the_max',
        'moonlight_chic',
        'little_campers',
        'first_fits',
        'desert_luxe',
        'pastel_pop',
        'everyday_clutter',
        'simtimates_collection',
        'bathroom_clutter',
        'greenhouse_haven',
        'basement_treasures',
        'grunge_revival',
        'book_nook',
        'poolside_splash',
        'modern_luxe',
        'goth_galore',
        'castle_estate',
        'urban_homage',
        'party_essentials',
        'riviera_retreat',
        'cozy_bistro',
        'storybook_nursery',
        'artist_studio',
        'sweet_slumber_party',
        'cozy_kitsch',
        'secret_sanctuary',
        'comfy_gamer',
        'casanova_cave',
        'refined_living_room',
        'business_chic',
        -- events
        'cozy_celebrations',
        'blast_from_the_past'
);

CREATE TYPE product_type AS ENUM(
        'base_game',
        'expansion_pack',
        'game_pack',
        'stuff_pack',
        'kit',
        'event'
);

CREATE TABLE products(
        id product_id PRIMARY KEY,
        name text NOT NULL,
        type product_type NOT NULL,
        release_date date NOT NULL
);

INSERT INTO products(id, type, name, release_date)
        VALUES
                -- base game
('base', 'base_game', 'The Sims 4', '09/02/2024'),
                -- expansions
('get_to_work', 'expansion_pack', 'Get To Work', '03/31/2015'),
('get_together', 'expansion_pack', 'Get Together', '12/08/2015'),
('city_living', 'expansion_pack', 'City Living', '11/1/2016'),
('cats_and_dogs', 'expansion_pack', 'Cats & Dogs', '11/10/2017'),
('seasons', 'expansion_pack', 'Seasons', '06/22/2018'),
('get_famous', 'expansion_pack', 'Get Famous', '11/16/2018'),
('island_living', 'expansion_pack', 'Island Living', '06/21/2019'),
('discover_university', 'expansion_pack', 'Discover University', '11/15/2019'),
('eco_lifestyle', 'expansion_pack', 'Eco Lifestyle', '06/05/2020'),
('snowy_escape', 'expansion_pack', 'Snowy Escape', '11/13/2020'),
('cottage_living', 'expansion_pack', 'Cottage Living', '07/22/2021'),
('high_school_years', 'expansion_pack', 'High School Years', '07/28/2022'),
('growing_together', 'expansion_pack', 'Growing Together', '03/16/2023'),
('horse_ranch', 'expansion_pack', 'Horse Ranch', '07/21/2023'),
('for_rent', 'expansion_pack', 'For Rent', '12/05/2023'),
('lovestruck', 'expansion_pack', 'Lovestruck', '07/25/2024'),
('life_and_death', 'expansion_pack', 'Life & Death', '10/31/2024'),
('businesses_and_hobbies', 'expansion_pack', 'Businesses & Hobbies', '03/06/2025'),
                -- game packs
('outdoor_retreat', 'game_pack', 'Outdoor Retreat', '01/13/2015'),
('spa_day', 'game_pack', 'Spa Day', '07/14/2015'),
('dine_out', 'game_pack', 'Dine Out', '06/07/2016'),
('vampires', 'game_pack', 'Vampires', '01/24/2017'),
('parenthood', 'game_pack', 'Parenthood', '05/30/2017'),
('jungle_adventure', 'game_pack', 'Jungle Adventure', '02/27/2018'),
('strangerville', 'game_pack', 'StrangerVille', '02/26/2019'),
('realm_of_magic', 'game_pack', 'Realm of Magic', '10/09/2019'),
('star_wars_journey_to_batuu', 'game_pack', 'Star Wars: Journey to Batuu', '09/08/2020'),
('dream_home_decorator', 'game_pack', 'Dream Home Decorator', '06/01/2021'),
('my_wedding_stories', 'game_pack', 'My Wedding Stories', '02/23/2022'),
('werewolves', 'game_pack', 'Werewolves', '06/16/2022'),
                -- stuff packs
('luxury_party', 'stuff_pack', 'Luxury Party', '05/19/2015'),
('perfect_patio', 'stuff_pack', 'Perfect Patio', '06/16/2015'),
('cool_kitchen', 'stuff_pack', 'Cool Kitchen', '08/11/2015'),
('spooky', 'stuff_pack', 'Spooky', '09/29/2015'),
('movie_hangout', 'stuff_pack', 'Movie Hangout', '01/12/2016'),
('romantic_garden', 'stuff_pack', 'Romantic Garden', '02/09/2016'),
('kids_room', 'stuff_pack', 'Kids Room', '06/28/2016'),
('backyard', 'stuff_pack', 'Backyard', '07/19/2016'),
('vintage_glamour', 'stuff_pack', 'Vintage Glamour', '12/06/2016'),
('bowling_night', 'stuff_pack', 'Bowling Night', '03/29/2017'),
('fitness', 'stuff_pack', 'Fitness', '06/20/2017'),
('toddler', 'stuff_pack', 'Toddler', '08/24/2017'),
('laundry_day', 'stuff_pack', 'Laundry Day', '01/16/2018'),
('my_first_pet', 'stuff_pack', 'My First Pet', '03/13/2018'),
('moschino', 'stuff_pack', 'Moschino', '09/03/2019'),
('tiny_living', 'stuff_pack', 'Tiny Living', '01/21/2020'),
('nifty_knitting', 'stuff_pack', 'Nifty Knitting', '07/28/2020'),
('paranormal', 'stuff_pack', 'Paranormal', '01/26/2021'),
('home_chef_hustle', 'stuff_pack', 'Home Chef Hustle', '09/28/2023'),
('crystal_creations', 'stuff_pack', 'Crystal Creations', '02/29/2024'),
                -- kits
('throwback_fit', 'kit', 'Throwback Fit', '03/02/2021'),
('country_kitchen', 'kit', 'Country Kitchen', '03/02/2021'),
('bust_the_dust', 'kit', 'Bust the Dust', '03/02/2021'),
('courtyard_oasis', 'kit', 'Courtyard Oasis', '05/18/2021'),
('modern_menswear', 'kit', 'Modern Menswear', '12/02/2021'),
('carnaval_streetwear', 'kit', 'Carnaval Streetwear', '02/03/2022'),
('decor_to_the_max', 'kit', 'Decor to the Max', '03/21/2022'),
('moonlight_chic', 'kit', 'Moonlight Chic', '05/26/2022'),
('little_campers', 'kit', 'Little Campers', '05/26/2022'),
('first_fits', 'kit', 'First Fits', '09/01/2022'),
('desert_luxe', 'kit', 'Desert Luxe', '09/14/2022'),
('pastel_pop', 'kit', 'Pastel Pop', '11/10/2022'),
('everyday_clutter', 'kit', 'Everyday Clutter', '11/10/2022'),
('simtimates_collection', 'kit', 'Simtimates Collection', '01/19/2023'),
('bathroom_clutter', 'kit', 'Bathroom Clutter', '01/19/2023'),
('greenhouse_haven', 'kit', 'Greenhouse Haven', '04/20/2023'),
('basement_treasures', 'kit', 'Basement Treasures', '04/20/2023'),
('grunge_revival', 'kit', 'Grunge Revival', '06/01/2023'),
('book_nook', 'kit', 'Book Nook', '06/01/2023'),
('poolside_splash', 'kit', 'Poolside Splash', '09/07/2023'),
('modern_luxe', 'kit', 'Modern Luxe', '09/07/2023'),
('goth_galore', 'kit', 'Goth Galore', '01/18/2024'),
('castle_estate', 'kit', 'Castle Estate', '01/18/2024'),
('urban_homage', 'kit', 'Urban Homage', '04/18/2024'),
('party_essentials', 'kit', 'Party ESsentials', '04/18/2024'),
('riviera_retreat', 'kit', 'Riviera Retreat', '05/30/2024'),
('cozy_bistro', 'kit', 'Cozy Bistro', '05/30/2024'),
('storybook_nursery', 'kit', 'Storybook Nursery', '09/19/2024'),
('artist_studio', 'kit', 'Artist Studio', '09/19/2024'),
('sweet_slumber_party', 'kit', 'Sweet Slumber Party', '11/14/2024'),
('cozy_kitsch', 'kit', 'Cozy Kitsch', '11/14/2024'),
('secret_sanctuary', 'kit', 'Secret Sanctuary', '01/16/2025'),
('comfy_gamer', 'kit', 'Comfy Gamer', '01/16/2025'),
('casanova_cave', 'kit', 'Casanova Cave', '01/16/2025'),
('refined_living_room', 'kit', 'Refined Living Room', '01/30/2025'),
('business_chic', 'kit', 'Business Chic', '01/30/2025'),
                -- events
('cozy_celebrations', 'event', 'Cozy Celebrations', '12/03/2024'),
('blast_from_the_past', 'event', 'Blast from the Past', '02/24/2025');

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DROP TABLE products;

DROP TYPE product_type;

DROP TYPE product_id;

-- +goose StatementEnd
